name: Workflows with large secrets

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/github-pages-deploy-action@master
      - name: Build and Deploy
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          BRANCH: gh-pages
