name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches: -master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          BRANCH: gh-pages
          FOLDER: build
