name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches: -master

steps:
  - name: Build and Deploy
    env:
      OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
      BRANCH: gh-pages
      FOLDER: build
